services:
  sketchyweatherapi:
    image: sketchyweatherapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5192:8080"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - API_KEY_WEATHER=
